---

- name: Install Dependencies
  hosts: frontendnodes
  tasks:

    - name: add repository keys
      become: yes
      apt_key:
        keyserver: "keyserver.ubuntu.com"
        id: "642AC823"
        state: present

    - name: add repositories
      become: yes
      apt_repository:
        repo: "deb https://dl.bintray.com/sbt/debian /"
        state: present
        update_cache: yes

    - name: install dependencies
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - sbt

- name: deploy code
  hosts: frontendnodes
  become: yes
  become_user: hadoop
  tasks:

    - name: prepare directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      items:
        - project

    - name: copy files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
      items:
        - build.sbt
        - network.scala
        - project/assembly.sbt
        - spark-submit.sh

    - name: fix permissions
      file:
        path: "{{ ansible_env.HOME }}/spark-submit.sh"
        state: file
        mode: 0755

    - name: package
      shell: "sbt package"
      args:
        chdir: "{{ ansible_env.HOME }}"

    - name: assembly
      shell: "sbt assembly"
      args:
        chdir: "{{ ansible_env.HOME }}"
