---


- name: Run the analysis
  hosts: frontendnodes
  become: yes
  become_user: hadoop
  tasks:

    - debug: msg="This may take a while"

    - name: run the analysis
      shell: "sh -lc './spark-submit.sh run'"
      args:
        chdir: "{{ ansible_env.HOME }}"
